name: Arduino CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino Compile
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:renesas_uno:unor4wifi"
          platforms: |
            - name: "arduino:renesas_uno"
          libraries: |
            - name: ArduinoBLE
            - name: ArduinoGraphics
            - name: Arduino_LED_Matrix
          sketch-paths: |
            - arduino/R4_Matrix_Controller
